# never push this file to git
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
# data: if i want to encode the data myself
stringData: # if i want kubernetes to encode the data for me in base64, i do this because here is the string
  mongo-url: "mongodb://mongo-srv/habits"
# secret not so secret if somebody have access to the cluster, because it in base64
