apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
  labels:
    app: {{.Chart.Name}}
spec:
  selector:
    app: {{.Chart.Name}}
  ports:
    - name: {{.Release.Name}}-listener
      protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetPort}}
  type: LoadBalancer
